👋🏻Halo Kak *{pushname}*, Aku adalah Bot Nizar yang di buat oleh Nizar Rahman menggunakan NodeJs untuk menjadi Asisten di WhatsApp.

╔═┅═❏『 *{namebot}* 』
┃ ✰ Founder: 𝐍𝐢𝐳𝐚𝐫𝐃𝐞𝐯
┃ ✰ nama: {namebot}
┃ ✰ {ucapan}
┃ ✰ tanggal: {tanggal}
┃ ✰ wib: {wib}
┃ ✰ wita: {wita}
┃ ✰ wit: {wit}
┃ ✰ limit: {limit}
┃ ✰ balance: {balance}
┃ ✰ xp: {xp}
┃ ✰ hari: {hari}
┃ ✰ status: {status}
┃ ✰ run: {runtime}
╚═━━━━═┅═❏


–––『 *ALL MENU BOT NIZAR* 』–––
╔═❏ *INFO PROMO BOT NIZAR*
┃• {prefix}promo
╚═━━━❏
╔═❏ *GENERAL MENU*
┃• {prefix}infobot
┃• {prefix}gcbot
┃• {prefix}owner
┃• {prefix}team
┃• {prefix}pay 
┃• {prefix}channel
┃• {prefix}changelog
┃• {prefix}ping
┃• {prefix}sewa
┃• {prefix}sewabot
┃• {prefix}buyprem
┃• {prefix}donasi
┃• {prefix}runtime
┃• {prefix}founder
┃• {prefix}loveyoubot
┃• rawr
┃• tai
╚═━━━❏
╔═❏ *INFO*
┃• {prefix}cekpremium
┃• {prefix}infocovid
┃• {prefix}infogempa
┃• {prefix}infounsur
┃• {prefix}kodebahasa
┃• {prefix}leavenosewa
┃• {prefix}level
┃• {prefix}limit
┃• {prefix}balance
┃• {prefix}buybalance
┃• {prefix}listban
┃• {prefix}listblock
┃• {prefix}listgroup
┃• {prefix}listgroupnosewa
┃• {prefix}listonline
┃• {prefix}listpremium
┃• {prefix}profile
┃• {prefix}status
┃• {prefix}topglobal
┃• {prefix}toplocal
┃• {prefix}websiteowner
┃• {prefix}igowner
╚═━━━❏
╔═❏ *GROUP*
┃• {prefix}absen
┃• {prefix}add
┃• {prefix}addbadword
┃• {prefix}addlist
┃• {prefix}addpoin
┃• {prefix}afk
┃• {prefix}admingroup
┃• {prefix}antibadword
┃• {prefix}antibadwordnokick
┃• {prefix}antibot
┃• {prefix}antidelete
┃• {prefix}antilink
┃• {prefix}antilinknokick
┃• {prefix}antiluar
┃• {prefix}antiviewonce
┃• {prefix}antiwame
┃• {prefix}antiwamenokick
┃• {prefix}blacklist
┃• {prefix}delblacklist
┃• {prefix}listblacklist
┃• {prefix}cekabsen
┃• {prefix}cekidgroup
┃• {prefix}cekpoint
┃• {prefix}ceksewa
┃• {prefix}ceksewabyid
┃• {prefix}cekwarn
┃• {prefix}createschedulecall
┃• {prefix}delbadword
┃• {prefix}delete
┃• {prefix}deleteabsen
┃• {prefix}deletepoin
┃• {prefix}deletetotalpesan
┃• {prefix}dellist
┃• {prefix}delultahku
┃• {prefix}delwarn
┃• {prefix}demote
┃• {prefix}demotedetector
┃• {prefix}descgc
┃• {prefix}done
┃• {prefix}gamemode
┃• {prefix}getlist
┃• {prefix}groupadmin
┃• {prefix}groupinfo
┃• {prefix}groupsetting
┃• {prefix}grouptime
┃• {prefix}hidetag
┃• {prefix}kick
┃• {prefix}leavegc
┃• {prefix}left
┃• {prefix}levelling
┃• {prefix}linkgc
┃• {prefix}revokelink
┃• {prefix}list
┃• {prefix}listbadword
┃• {prefix}listpoint
┃• {prefix}listtotalpesan
┃• {prefix}listultah
┃• {prefix}listwarn
┃• {prefix}mulaiabsen
┃• {prefix}mute
┃• {prefix}promote
┃• {prefix}promotedetector
┃• {prefix}proses
┃• {prefix}refreshgroup
┃• {prefix}resetbadword
┃• {prefix}resetlist
┃• {prefix}resetpoint
┃• {prefix}resettotalpesan
┃• {prefix}resetwarn
┃• {prefix}setdescgc
┃• {prefix}setnamegc
┃• {prefix}setopen
┃• {prefix}setclose
┃• {prefix}setppgc
┃• {prefix}setppgcpanjang
┃• {prefix}setproses
┃• {prefix}setdone
┃• {prefix}setwarn
┃• {prefix}setwelcome
┃• {prefix}setleft
┃• {prefix}setwelcometype
┃• {prefix}setlefttype
┃• {prefix}sider
┃• {prefix}tagall
┃• {prefix}tfpoint
┃• {prefix}totag
┃• {prefix}totalpesan
┃• {prefix}ultahku
┃• {prefix}vote
┃• {prefix}warn
┃• {prefix}welcome
╚═━━━❏
╔═❏ *TOOLS*
┃• {prefix}aiimage
┃• {prefix}nexara
┃• {prefix}blur
┃• {prefix}cekplatform
┃• {prefix}ehex
┃• {prefix}dhex
┃• {prefix}ebase64
┃• {prefix}dbase64
┃• {prefix}enc
┃• {prefix}dec
┃• {prefix}fakereply
┃• {prefix}hartatahta
┃• {prefix}jadianime
┃• {prefix}kirim
┃• {prefix}confess
┃• {prefix}menfess
┃• {prefix}nulis
┃• {prefix}folio
┃• {prefix}ocr
┃• {prefix}openai
┃• {prefix}poll
┃• {prefix}ptvtovideo
┃• {prefix}qrcode
┃• {prefix}qrcodereader
┃• {prefix}readmore
┃• {prefix}readviewonce
┃• {prefix}removebackground
┃• {prefix}screenshot
┃• {prefix}shortlink
┃• {prefix}myemail
┃• {prefix}getemail
┃• {prefix}tomp3
┃• {prefix}tovn
┃• {prefix}toquickvideo
┃• {prefix}tourl
┃• {prefix}translate
┃• {prefix}tts
┃• {prefix}tts2
┃• {prefix}upscale
┃• {prefix}voicejapan
┃• {prefix}halah
┃• {prefix}hilih
┃• {prefix}huluh
┃• {prefix}heleh
┃• {prefix}holoh
┃• {prefix}wait
┃• {prefix}ytcomment
╚═━━━❏
╔═❏ *GAME*
┃• {prefix}akinator
┃• {prefix}akinatorstart
┃• {prefix}akinatorstop
┃• {prefix}asahotak
┃• {prefix}buylimit
┃• {prefix}cekkhodam
┃• {prefix}caklontong
┃• {prefix}dare
┃• {prefix}family100
┃• {prefix}hint
┃• {prefix}math
┃• {prefix}nyerah
┃• {prefix}redeem
┃• {prefix}sambungkata
┃• {prefix}siapakahaku
┃• {prefix}sloth
┃• {prefix}suit
┃• {prefix}susunkalimat
┃• {prefix}susunkata
┃• {prefix}susunlirik
┃• {prefix}tebakbendera
┃• {prefix}tebakbom
┃• {prefix}tebakchara
┃• {prefix}tebakgambar
┃• {prefix}tebakkata
┃• {prefix}tebaklagu
┃• {prefix}tebaklaguanime
┃• {prefix}tebaklagukpop
┃• {prefix}tekateki
┃• {prefix}tfbalance
┃• {prefix}truth
┃• {prefix}werewolf
╚═━━━❏
╔═❏ *RANDOM*
┃• {prefix}alay
┃• {prefix}apakah
┃• {prefix}faktaunik
┃• {prefix}husbu
┃• {prefix}jadian
┃• {prefix}kapankah
┃• {prefix}katabijak
┃• {prefix}loli
┃• {prefix}pantun
┃• {prefix}ppcouple
┃• {prefix}puisi
┃• {prefix}quotesanime
┃• {prefix}randomanime
┃• {prefix}randommeme
┃• {prefix}randomtag
┃• {prefix}rate
┃• {prefix}siapakah
┃• {prefix}neko
┃• {prefix}waifu
╚═━━━❏
╔═❏ *ANONYMOUS*
┃• {prefix}anonymous
┃• {prefix}start
┃• {prefix}next
┃• {prefix}leave
┃• {prefix}send
╚═━━━❏
╔═❏ *SEARCH*
┃• {prefix}artinama
┃• {prefix}alkitab
┃• {prefix}brainly
┃• {prefix}cuaca
┃• {prefix}dorama
┃• {prefix}google
┃• {prefix}googleimage
┃• {prefix}igstalk
┃• {prefix}ipchecker
┃• {prefix}jadwalshalat
┃• {prefix}lirik
┃• {prefix}otakudesuinfo
┃• {prefix}otakudesuongoing
┃• {prefix}otakudesu
┃• {prefix}pinterest
┃• {prefix}play
┃• {prefix}wikipedia
┃• {prefix}ytsearch
╚═━━━❏
╔═❏ *STICKER*
┃• {prefix}attp
┃• {prefix}quickchat
┃• {prefix}semoji
┃• {prefix}semojimix
┃• {prefix}setwm
┃• {prefix}sticker
┃• {prefix}stickercircle
┃• {prefix}stickerinfo
┃• {prefix}smeme
┃• {prefix}snobg
┃• {prefix}stickerwm
┃• {prefix}takesticker
┃• {prefix}telestick
┃• {prefix}toimg
┃• {prefix}trigger
┃• {prefix}ttp
╚═━━━❏
╔═❏ *DOWNLOAD*
┃• {prefix}facebook
┃• {prefix}igstory
┃• {prefix}igdl
┃• {prefix}igtv
┃• {prefix}igreel
┃• {prefix}mediafire
┃• {prefix}otakudesudl
┃• {prefix}pindl
┃• {prefix}threads
┃• {prefix}tiktoknowm
┃• {prefix}tiktokwm
┃• {prefix}tiktokmusic
┃• {prefix}tt
┃• {prefix}ttmp3
┃• {prefix}twitterdl
┃• {prefix}ytmp3
┃• {prefix}ytmp4
╚═━━━❏
╔═❏ *TEXTMAKER*
┃• {prefix}lightglow
┃• {prefix}thunder
┃• {prefix}blackpink
┃• {prefix}bear
┃• {prefix}cloud
┃• {prefix}neonlight
┃• {prefix}sand
┃• {prefix}dropwater
┃• {prefix}magma
┃• {prefix}glow
┃• {prefix}neon
┃• {prefix}window
┃• {prefix}sky
┃• {prefix}pencil
┃• {prefix}cartoon
┃• {prefix}spacetext
┃• {prefix}greenneon
┃• {prefix}bisnissign
┃• {prefix}bokeh
┃• {prefix}firework
┃• {prefix}batman
┃• {prefix}holo
┃• {prefix}narutologo
┃• {prefix}glitch
┃• {prefix}thor
┃• {prefix}wolf
┃• {prefix}phlogo
┃• {prefix}avangers
┃• {prefix}marvel
┃• {prefix}halloween
┃• {prefix}graffiti
╚═━━━❏
╔═❏ *OWNER*
┃• {prefix}addbalance
┃• {prefix}addlevel
┃• {prefix}addlimit
┃• {prefix}addpremium
┃• {prefix}addrespon
┃• {prefix}addsewa
┃• {prefix}addxp
┃• {prefix}anticall
┃• {prefix}anticallnoblock
┃• {prefix}antideletepc
┃• {prefix}autoread
┃• {prefix}autotype
┃• {prefix}ban
┃• {prefix}block
┃• {prefix}broadcast
┃• {prefix}bccancel
┃• {prefix}bcconfirm
┃• {prefix}bcgroup
┃• {prefix}bcgchidetag
┃• {prefix}bchidetag
┃• {prefix}bcmember
┃• {prefix}bcpremium
┃• {prefix}bcpc
┃• {prefix}bcsewa
┃• {prefix}bcstat
┃• {prefix}buttonmode
┃• {prefix}call
┃• {prefix}cekaccount
┃• {prefix}cekopenaikey
┃• {prefix}chatgroup
┃• {prefix}clearchat
┃• {prefix}createbutton
┃• {prefix}createlist
┃• {prefix}createredeem
┃• {prefix}createlist
┃• {prefix}createthumbnail
┃• {prefix}delbalance
┃• {prefix}dellevel
┃• {prefix}dellimit
┃• {prefix}delpremium
┃• {prefix}deleteredeem
┃• {prefix}delrespon
┃• {prefix}delsewa
┃• {prefix}delxp
┃• {prefix}golink
┃• {prefix}grabcontact
┃• {prefix}grouponlypremium
┃• {prefix}inforedeem
┃• {prefix}inviteme
┃• {prefix}join
┃• {prefix}leaveall
┃• {prefix}leavegcbyid
┃• {prefix}levellingpc
┃• {prefix}listrespon
┃• {prefix}listsewa
┃• {prefix}mutebc
┃• {prefix}mutebyid
┃• {prefix}mycontacts
┃• {prefix}onlygroup
┃• {prefix}onlyindo
┃• {prefix}onlyprem
┃• {prefix}pconlyprem
┃• {prefix}public
┃• {prefix}publicbyid
┃• {prefix}react
┃• {prefix}refreshpremiumlist
┃• {prefix}resetanonymous
┃• {prefix}resetbalance
┃• {prefix}resetlevel
┃• {prefix}resetxp
┃• {prefix}resetlimit
┃• {prefix}resetpremium
┃• {prefix}resetresponsee
┃• {prefix}self
┃• {prefix}selfbyid
┃• {prefix}setbio
┃• {prefix}setdefaultweltype
┃• {prefix}setname
┃• {prefix}setopenaikey
┃• {prefix}setpp
┃• {prefix}setpppanjang
┃• {prefix}unban
┃• {prefix}unblock
┃• {prefix}unreact
┃• {prefix}upres
┃• {prefix}upsw
┃• {prefix}upswgroup
┃• {prefix}upswpremium
┃• {prefix}videocall
╚═━━━━━━━━━━━━━❏
https://whatsapp.com/channel/0029VaMBdiEATRSkHXl9qe0N
𝗙𝗼𝘂𝗻𝗱𝗲𝗿: 𝗡𝗶𝘇𝗮𝗿 𝗥𝗮𝗵𝗺𝗮𝗻 𝗙𝗮𝗱𝗶𝗹𝗹𝗮𝗵